complex:
  entity_embedder:
    dropout: 0.046551704
    regularize_weight: 8.9E-20
  relation_embedder:
    dropout: 0.082643807
    regularize_weight: 0.000747368
dataset:
  name: wnrr
eval:
  batch_size: 512
  metrics_per:
    relation_type: true
  trace_level: example
import:
- reciprocal_relations_model
- complex
lookup_embedder:
  dim: 128
  initialize: xavier_normal_
  initialize_args:
    xavier_normal_:
      gain: 1.0
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
  num_samples:
    o: 6
    p: -1
    s: 6
reciprocal_relations_model:
  base_model:
    type: complex
train:
  auto_correct: true
  batch_size: 1024
  loss: bce_self_adversarial
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 400
  optimizer: Adam
  optimizer_args:
    lr: 0.000331847
  type: negative_sampling
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 7
user:
  bce_self_adversarial_temperature: 1.0
