complex:
  entity_embedder:
    regularize: lp
    regularize_args:
      p: 2
      weighted: false
    dropout: 0.047619581
    regularize_weight: 1.48E-18
  relation_embedder:
    regularize: lp
    regularize_args:
      weighted: false
      dropout: 0.443125665
      regularize_weight: 1.44E-18
dataset:
  name: fb15k-237
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- complex
- reciprocal_relations_model
lookup_embedder:
  dim: 128
  initialize: uniform_
  initialize_args:
    uniform_:
      a: -0.31095556
model: complex
negative_sampling:
  implementation: batch
  num_samples:
    p: -1
reciprocal_relations_model:
  base_model:
    type: complex
train:
  auto_correct: true
  batch_size: 512
  loss: kl
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 800
  optimizer: Adagrad
  optimizer_args:
    lr: 0.50337579
  type: 1vsAll
  label_smoothing: 0.3
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
