dataset:
  name: fb15k-237
distmult:
  entity_embedder:
    dropout: 0.370197177
    regularize_weight: 5.82E-12
  relation_embedder:
    dropout: 0.280091763
    regularize_weight: 6.77E-11
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- distmult
- reciprocal_relations_model
lookup_embedder:
  dim: 128
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.80619994
    uniform_:
      a: -0.036706782
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize: ''
  regularize_args:
    weighted: true
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
  num_samples:
    p: -1
reciprocal_relations_model:
  base_model:
    type: distmult
train:
  auto_correct: true
  batch_size: 512
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 1
    threshold: 0.0001
  max_epochs: 800
  optimizer: Adam
  optimizer_args:
    lr: 0.000633628
  type: 1vsAll
  label_smoothing: 0.0
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
