dataset:
  name: wnrr
distmult:
  entity_embedder:
    dropout: 0.047619581
    regularize_weight: 1.44E-18
  relation_embedder:
    dropout: 0.443125665
    regularize_weight: 1.44E-18
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- distmult
- reciprocal_relations_model
lookup_embedder:
  dim: 128
  initialize: uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 9.08E-05
    uniform_:
      a: -0.31095556
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 2
    weighted: false
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
  num_samples:
    p: -1
reciprocal_relations_model:
  base_model:
    type: distmult
train:
  auto_correct: true
  batch_size: 512
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 800
  optimizer: Adagrad
  optimizer_args:
    lr: 0.50337579
  type: 1vsAll
  label_smoothing: 0.3
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
