dataset:
  name: wnrr
distmult:
  entity_embedder:
    dropout: 0.046551704
    regularize_weight: 8.9E-20
  relation_embedder:
    dropout: 0.082643807
    regularize_weight: 0.000747368
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- distmult
- reciprocal_relations_model
lookup_embedder:
  dim: 128
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.000214974
    uniform_:
      a: -0.147714555
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize: ''
  regularize_args:
    weighted: true
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
  num_samples:
    s: 6
    p: -1
    o: 6
reciprocal_relations_model:
  base_model:
    type: distmult
train:
  auto_correct: true
  batch_size: 1024
  loss: bce_self_adversarial
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 800
  optimizer: Adam
  optimizer_args:
    lr: 0.000331847
  type: negative_sampling
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
user:
  bce_self_adversarial_temperature: 1.0
