dataset:
  name: fb15k-237
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- rescal
- reciprocal_relations_model
lookup_embedder:
  dim: 128
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.0143570796
    uniform_:
      a: -0.31064854
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize: ''
model: reciprocal_relations_model
negative_sampling:
  num_samples:
    o: 155
    p: -1
    s: 22
reciprocal_relations_model:
  base_model:
    type: rescal
train:
  auto_correct: true
  batch_size: 128
  loss: bce
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  max_epochs: 800
  optimizer: Adagrad
  optimizer_args:
    lr: 0.017017577
  type: negative_sampling
rescal:
  entity_embedder:
    regularize: lp
    regularize_args:
      p: 3
      weighted: true
    dropout: 0.346598208
    regularize_weight: 1.21664938530715E-12
  relation_embedder:
    regularize: lp
    regularize_args:
      p: 3
      weighted: true
    dim: 16384
    dropout: -0.3034232855
    regularize_weight: 4.79694729426325E-14
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
