dataset:
  name: wnrr
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- reciprocal_relations_model
- rescal
lookup_embedder:
  dim: 256
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.0000365437581053422
    uniform_:
      a: -0.655262252
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize: ''
  regularize_args:
    weighted: true
model: rescal
negative_sampling:
  implementation: batch
  num_samples:
    p: -1
reciprocal_relations_model:
  base_model:
    type: rescal
rescal:
  entity_embedder:
    regularize: lp
    regularize_args:
      p: 3
      weighted: true
    dropout: -0.092702359
    regularize_weight: 0.0000108584236095707
  relation_embedder:
    regularize: lp
    regularize_args:
      p: 3
      weighted: true
    dim: -1
    dropout: -0.4612573534
    regularize_weight: 6.55217798803444E-06
train:
  auto_correct: true
  batch_size: 512
  loss: kl
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 9
    threshold: 0.0001
  max_epochs: 800
  optimizer: Adam
  optimizer_args:
    lr: 0.0024573814
  type: 1vsAll
  label_smoothing: 0.0
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
