dataset:
  name: wnrr
eval:
  batch_size: 16
  metrics_per:
    relation_type: true
  trace_level: example
import:
- rotate
- reciprocal_relations_model
lookup_embedder:
  dim: 500
  initialize: xavier_uniform_
  initialize_args:
      xavier_uniform_:
        gain: 1.0
rotate:
  entity_embedder:
    regularize: lp
    dropout: 0.0
    regularize_args:
        p: 2
        weighted: false
    regularize_weight: 0.0
  relation_embedder:
    regularize: lp
    dropout: 0.0
    regularize_args:
        p: 2
        weighted: false
    regularize_weight: 0.0
  normalize_phases: True
model: rotate
negative_sampling:
  num_samples:
    o: 1024
    p: -1
    s: 1024
reciprocal_relations_model:
  base_model:
    type: rotate
train:
  auto_correct: true
  subbatch_auto_tune: true
  batch_size: 512
  loss: bce_self_adversarial
  loss_arg: 6.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.001
  max_epochs: 800
  optimizer: Adam
  optimizer_args:
    lr: 0.00005
  type: negative_sampling
  label_smoothing: 0.0
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
user:
  bce_self_adversarial_temperature: 0.5
