dataset:
  name: fb15k-237
eval:
  batch_size: 16
  metrics_per:
    relation_type: true
  trace_level: example
import:
- transe
- reciprocal_relations_model
lookup_embedder:
  dim: 1000
  initialize: xavier_uniform_
  initialize_args:
      xavier_uniform_:
        gain: 1.0
transe:
  entity_embedder:
    regularize: lp
    dropout: 0.0
    regularize_args:
        p: 2
        weighted: false
    regularize_weight: 0.0
  relation_embedder:
    regularize: lp
    dropout: 0.0
    regularize_args:
        p: 2
        weighted: false
    regularize_weight: 0.0
model: transe
negative_sampling:
  num_samples:
    o: 256
    p: -1
    s: 256
reciprocal_relations_model:
  base_model:
    type: transe
train:
  auto_correct: true
  subbatch_auto_tune: true
  batch_size: 1024
  loss: bce
  loss_arg: 9.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  max_epochs: 800
  optimizer: Adam
  optimizer_args:
    lr: 0.00005
  type: negative_sampling
  label_smoothing: 0.0
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
