relational_tucker3:
  entity_embedder:
    dropout: 0.2
  relation_embedder:
    dropout: 0.2
dataset:
  name: wnrr
eval:
  batch_size: 128
  metrics_per:
    relation_type: true
  trace_level: example
import:
- relational_tucker3
- reciprocal_relations_model
lookup_embedder:
  dim: 200
  initialize: xavier_normal_
  initialize_args:
    xavier_normal_:
      gain: 1.0
  regularize_args:
    p: 1
    weighted: false
model: relational_tucker3
negative_sampling:
  implementation: batch
  num_samples:
    p: -1
reciprocal_relations_model:
  base_model:
    type: relational_tucker3
train:
  auto_correct: true
  batch_size: 128
  loss: bce
  loss_arg: 0.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 10000
    threshold: 0.0001
  max_epochs: 400
  optimizer: Adam
  optimizer_args:
    lr: 0.0005
  type: 1vsAll
  label_smoothing: 0.0
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.0001
    patience: 7
