job.type: train
dataset.name: toy

train:
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4
  type: KvsAll

model: complex
lookup_embedder:
  dim: 100
  regularize_weight: 0.8e-7
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.1
