job.type: train
dataset.name: toy

model: transe

train:
  batch_size: 256
  loss: margin_ranking
  loss_arg: 4.0
  max_epochs: 200
  optimizer: Adagrad
  optimizer_args:
    lr: 0.1
  type: negative_sampling

valid:
  early_stopping.patience: 5
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test

eval:
  batch_size: 512

negative_sampling:
  num_samples.s: 3  # default: p=0; o=s
  sampling_type: uniform

lookup_embedder:
  dim: 128
  regularize: l2
  regularize_args:
    weight: 1.e-05
    weighted: False

transe:
  l_norm: 1.
